=== proyectocomundam/InmobiliariaCasasMartin/inmobiliariacasasmartin.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
<!-- Esquema XML munyecas rusas -->
<xsd:element name="inmobiliariacasasmartin">
    <xsd:complexType>
        <xsd:sequence>
            <!-- Elemento complejo VISITA -->
            <xsd:element name="visita">
                <xsd:complexType>
                    <xsd:sequence>
                        <!-- Elemento complejo PROPIEDAD -->
                        <xsd:element name="propiedad">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="ref_pr" type="xsd:integer"/>
                                    <xsd:element name="direccion_pr" type="xsd:string"/>
                                    <xsd:element name="numero" type="xsd:integer"/>
                                    <xsd:element name="localidad" type="xsd:string" default="Vecindario"/>
                                    <xsd:element name="m2" type="xsd:float"/>
                                    <xsd:element name="n_hab" type="xsd:integer"/>
                                    <xsd:element name="propietario" type="xsd:string"/>
                                    <xsd:element name="tlf_propietario" type="xsd:string">
                                        <xsd:simpleType>
                                        <!-- Restriccion: debe tener 9 de longitud -->
                                            <xsd:restriction base="xsd:string">
                                                <xsd:length value="9"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="particular_banco" type="xsd:string"/>
                                    <xsd:element name="financiacion" type="xsd:float"/>
                                    <xsd:element name="precio">
                                        <xsd:simpleType>
                                        <!-- Restriccion: 2 decimales -->
                                            <xsd:restriction base="xsd:decimal">
                                                <xsd:fractionDigits value="2"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="captador" type="xsd:string"/>                                  
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="cliente">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="cod_cl" type="xsd:integer"/>
                                    <xsd:element name="dni_cl">
                                    <xsd:simpleType>
                                    <!-- Restriccion: debe tener 9 de longitud -->
                                            <xsd:restriction base="xsd:string">
                                                <xsd:length value="9"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="nom_cl" type="string"/>
                                    <xsd:element name="ap_cl" type="string"/>
                                    <xsd:element name="email_cl" type="string"/>
                                    <xsd:element name="tlf_cl" type="string">
                                        <xsd:simpleType>
                                        <!-- Restriccion: debe tener 9 de longitud -->
                                            <xsd:restriction base="xsd:string">
                                                <xsd:length value="9"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="estado">
                                        <xsd:simpleType>
                                        <!-- Restriccion: solo puede ser uno de estos valores -->
                                            <xsd:restriction base="xs:string">
                                                <xsd:enumeration value="Buscando"/>
                                                <xsd:enumeration value="Ya no busca"/>
                                                <xsd:enumeration value="Compró con nosotros"/>
                                                <xsd:enumeration value="Compró con otros">
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="comercial" type="string"/>
                                    <xsd:element name="administrador" type="string"/>
                                    <xsd:element name="oficina" type="string"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="fecha_visita" type="date"/>
                        <xsd:element name="hora_visita" type="time"/>
                    </xsd:sequence>
                </xsd:complexType>
        </xsd:sequence>
        <xsd:attribute name="dni" type="xsd:string" default="98765432B">
            <xsd:simpleType>
            <!-- Restriccion: debe tener 9 de longitud -->
                <xsd:restriction base="xs:string">
                    <xsd:length value="9"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="movil" type="xsd:string">
            <xsd:simpleType>
            <!-- Restriccion: debe tener 9 de longitud -->
                <xsd:restriction base="xs:string">
                    <xsd:length value="9"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="tlf" type="xsd:string" default="928282828">
            <xsd:simpleType>
            <!-- Restriccion: debe tener 9 de longitud -->
                <xsd:restriction base="xs:string">
                    <xsd:length value="9"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
</xsd:element>

=== proyectocomundam/InmobiliariaCasasMartin/index.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="inmobiliariacasasmartin.xsl"?>
<inmobiliariacasasmartin codigo="123456" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="inmobiliariacasasmartin.xsd">
    <visita>
        <propiedad>
            <ref_pr>10001</ref_pr>
            <direccion_pr>C/Che-guevara</direccion_pr>
            <numero>70</numero>
            <localidad>Vecindario</localidad>
            <m2>90.00</m2>
            <n_hab>3</n_hab>
            <propietario>Josefa Suarez</propietario>
            <tlf_propietario>617776226</tlf_propietario>
            <particular_banco>Particular</particular_banco>
            <financiacion>100</financiacion>
            <precio>95000,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>1</cod_cl>
            <dni_cl>99999999Z</dni_cl>
            <nom_cl>Carla</nom_cl>
            <ap_cl>Gonzalez Martin</ap_cl>
            <email_cl>cgm@gmail.com</email_cl>
            <tlf_cl>666554433</tlf_cl>
            <estado>Buscando</estado>
            <comercial movil="634567890">Maria Hernandez Casado</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>30/01/2019</fecha_visita>
        <hora_visita>11:45:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10002</ref_pr>
            <direccion_pr>Av Canarias</direccion_pr>
            <numero>53</numero>
            <localidad>Vecindario</localidad>
            <m2>60.00</m2>
            <n_hab>2</n_hab>
            <propietario>Luis Martinez</propietario>
            <tlf_propietario>654655678</tlf_propietario>
            <particular_banco>Particular</particular_banco>
            <financiacion>90</financiacion>
            <precio>100000,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>7</cod_cl>
            <dni_cl>35533566M</dni_cl>
            <nom_cl>Curro</nom_cl>
            <ap_cl>Jimenez Gallegos</ap_cl>
            <email_cl>curro@gmail.com</email_cl>
            <tlf_cl>612345678</tlf_cl>
            <estado>Buscando</estado>
            <comercial movil="676543210">Carlos Suarez Gonzalez</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>28/02/2019</fecha_visita>
        <hora_visita>16:15:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10005</ref_pr>
            <direccion_pr>C/Timimi</direccion_pr>
            <numero>73</numero>
            <localidad>Ingenio</localidad>
            <m2>60.00</m2>
            <n_hab>2</n_hab>
            <propietario>Servihabitat</propietario>
            <tlf_propietario>928666666</tlf_propietario>
            <particular_banco>Banco</particular_banco>
            <financiacion>100</financiacion>
            <precio>93500,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>3</cod_cl>
            <dni_cl>77777777X</dni_cl>
            <nom_cl>Noelia</nom_cl>
            <ap_cl>Diaz Goyes</ap_cl>
            <email_cl>n@hotmail.com</email_cl>
            <tlf_cl>622322332</tlf_cl>
            <estado>Buscando</estado>
            <comercial movil="665432109">Pablo Monta침ez Vega</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>10/01/2019</fecha_visita>
        <hora_visita>16:30:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10005</ref_pr>
            <direccion_pr>C/Timimi</direccion_pr>
            <numero>73</numero>
            <localidad>Ingenio</localidad>
            <m2>60.00</m2>
            <n_hab>2</n_hab>
            <propietario>Servihabitat</propietario>
            <tlf_propietario>928666666</tlf_propietario>
            <particular_banco>Banco</particular_banco>
            <financiacion>100</financiacion>
            <precio>93500,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>5</cod_cl>
            <dni_cl>77888787P</dni_cl>
            <nom_cl>Pedro</nom_cl>
            <ap_cl>Fernandez Diaz</ap_cl>
            <email_cl>p@gmail.com</email_cl>
            <tlf_cl>777886655</tlf_cl>
            <estado>Ya no busca</estado>
            <comercial movil="665432109">Pablo Monta침ez Vega</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>10/01/2019</fecha_visita>
        <hora_visita>10:00:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10006</ref_pr>
            <direccion_pr>Av America</direccion_pr>
            <numero>150</numero>
            <localidad>Ingenio</localidad>
            <m2>100.00</m2>
            <n_hab>3</n_hab>
            <propietario>Servihabitat</propietario>
            <tlf_propietario>928666666</tlf_propietario>
            <particular_banco>Banco</particular_banco>
            <financiacion>100</financiacion>
            <precio>130600,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>8</cod_cl>
            <dni_cl>31234567N</dni_cl>
            <nom_cl>Alberto</nom_cl>
            <ap_cl>Baez Diaz</ap_cl>
            <email_cl>al@gmail.com</email_cl>
            <tlf_cl>611278979</tlf_cl>
            <estado>Compr칩 con nosotros</estado>
            <comercial movil="634567890">Maria Hernandez Casado</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>07/02/2019</fecha_visita>
        <hora_visita>12:15:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10007</ref_pr>
            <direccion_pr>C/Tomas Morales</direccion_pr>
            <numero>58</numero>
            <localidad>Las Palmas</localidad>
            <m2>90.00</m2>
            <n_hab>3</n_hab>
            <propietario>Casaktua</propietario>
            <tlf_propietario>928333333</tlf_propietario>
            <particular_banco>Banco</particular_banco>
            <financiacion>100</financiacion>
            <precio>200000,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>6</cod_cl>
            <dni_cl>54544533O</dni_cl>
            <nom_cl>Maria</nom_cl>
            <ap_cl>Perez Suarez</ap_cl>
            <email_cl>mps@gmail.com</email_cl>
            <tlf_cl>622332233</tlf_cl>
            <estado>Compr칩 con nosotros</estado>
            <comercial movil="676543210">Carlos Suarez Gonzalez</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>30/01/2019</fecha_visita>
        <hora_visita>09:30:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10008</ref_pr>
            <direccion_pr>C/Moralito</direccion_pr>
            <numero>110</numero>
            <localidad>Doctoral</localidad>
            <m2>50.00</m2>
            <n_hab>1</n_hab>
            <propietario>Casaktua</propietario>
            <tlf_propietario>928333333</tlf_propietario>
            <particular_banco>Banco</particular_banco>
            <financiacion>100</financiacion>
            <precio>57000,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>2</cod_cl>
            <dni_cl>88888888Y</dni_cl>
            <nom_cl>Marco</nom_cl>
            <ap_cl>Santana Alvarez</ap_cl>
            <email_cl>msan@gmail.com</email_cl>
            <tlf_cl>611212121</tlf_cl>
            <estado>Buscando</estado>
            <comercial movil="634567890">Maria Hernandez Casado</comercial>
            <administrador email="luis@cmartin.es">Luis Rodriguez Sanchez</administrador>
            <oficina tlf="928282828">Av Canarias, 95</oficina>
        </cliente>
        <fecha_visita>30/01/2019</fecha_visita>
        <hora_visita>09:30:00</hora_visita>
    </visita>
    <visita>
        <propiedad>
            <ref_pr>10009</ref_pr>
            <direccion_pr>C/Magallanes</direccion_pr>
            <numero>15</numero>
            <localidad>Playa de Arinaga</localidad>
            <m2>70.00</m2>
            <n_hab>2</n_hab>
            <propietario>Roberto Pesquero</propietario>
            <tlf_propietario>678900105</tlf_propietario>
            <particular_banco>Particular</particular_banco>
            <financiacion>100</financiacion>
            <precio>78500,00</precio>
            <captador dni="98765432B">Marco Alvarez Perdomo</captador>
        </propiedad>
        <cliente>
            <cod_cl>4</cod_cl>
            <dni_cl>66666666W</dni_cl>
            <nom_cl>David</nom_cl>
            <ap_cl>Cruz Fernandez</ap_cl>
            <email_cl>david@gmail.com</email_cl>
